#!/bin/env bash
#$ -N genomasena
#$ -o $JOB_NAME.log
#$ -e $JOB_NAME.error
#$ -S /bin/bash
 
date
echo "===== Beginning pipeline ====="
 
mamba activate 
/mnt/atgc-d2/sur/modules/pkgs/enaBrowserTools/1.7/python3/enaGroupGet -g wgs -f fasta -d /mnt/atgc-d2/sur/shared_data/genomas_karasov_2018 PRJEB24450

echo "===== Pipeline done ====="
date
